import mysql.connector as sql
import sys
mycon=sql.connect(host="localhost",user="root",passwd="7489895821",database="library")
cursor=mycon.cursor(buffered=True)
cursor.execute("""
CREATE TABLE IF NOT EXISTS `lib` (
  `BOOK_CODE` int(5) NOT NULL,
  `book_name` char(35) NOT NULL,
  `stu_name` char(15) DEFAULT NULL,
  `stu_class` int(2) DEFAULT NULL,
  `issue_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `author_publisher` char(25) DEFAULT NULL,
  `Genre` char(15) DEFAULT NULL,
  `availability` char(15) DEFAULT 'available',
  PRIMARY KEY (`BOOK_CODE`))
""")
cursor.execute("""
INSERT INTO `lib` (`BOOK_CODE`, `book_name`, `stu_name`, `stu_class`, `issue_date`, `due_date`, `author_publisher`, `Genre`, `availability`) VALUES
	(10001, 'IP Python', 'Aryan', 12, '2019-10-03', '2019-10-18', 'Sumita Arora', 'Education', 'not available'),
	(10002, 'Maths', 'Rahul', 10, '2019-10-03', '2019-10-20', 'RD Sharma', 'Education', 'not available'),
	(10003, 'Flamingo', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10004, 'Chemistry', NULL, NULL, NULL, NULL, 'Pradeep', 'Education', 'available'),
	(10005, 'Physics', NULL, NULL, NULL, NULL, 'HC Verma', 'Education', 'available'),
	(10006, 'Song of Ice and Fire', NULL, NULL, NULL, NULL, 'George R Martin', 'Fantasy', 'available'),
	(10007, 'Harry Potter', NULL, NULL, NULL, NULL, 'J.K Rowling', 'Fantasy', 'available'),
	(10008, 'Sherlok Holmes', NULL, NULL, NULL, NULL, 'Sir Aurthor Conan Doyle', 'Mystry', 'available'),
	(10009, 'Murder On The Orient Express', NULL, NULL, NULL, NULL, 'Agatha Cristie', 'Mystry', 'available'),
	(10010, 'The Girl With The Dragon Tatoo', NULL, NULL, NULL, NULL, 'Steig Larson', 'Mystry', 'available'),
	(10011, 'Lord of the rings', NULL, NULL, NULL, NULL, 'G.R Tolkien', 'Fantasy', 'available'),
	(10012, 'The Three Musketeers', NULL, NULL, NULL, NULL, 'Alexander Duman', 'Fiction', 'available'),
	(10013, 'Star Ship Troopers', NULL, NULL, NULL, NULL, 'Robert A.Heainlien', 'Fiction', 'available'),
	(10014, 'Alice In Wonderland', NULL, NULL, NULL, NULL, 'Lewis Caroll', 'Fiction', 'available'),
	(10015, 'The Time Machine', NULL, NULL, NULL, NULL, 'H.G Wells', 'Fiction', 'available'),
	(10016, 'Frankinstein', NULL, NULL, NULL, NULL, 'Mary Shelly', 'Fiction', 'available'),
	(10017, 'The Notebook', NULL, NULL, NULL, NULL, 'Nicholas Sparks', 'Romantic', 'available'),
	(10018, 'Romeo and Juliet', NULL, NULL, NULL, NULL, 'William Shakespere', 'Romantic', 'available'),
	(10019, 'The Fault In Our Stars', NULL, NULL, NULL, NULL, 'John Greene', 'Romantic', 'available'),
	(10020, 'Beautiful Disaster', NULL, NULL, NULL, NULL, 'Jamie Mcguire', 'Romantic', 'available'),
	(10021, 'The Diary Of A Young Girl', NULL, NULL, NULL, NULL, 'Anne frank', 'Biography', 'available'),
	(10022, 'Steve Jobs', NULL, NULL, NULL, NULL, 'Walter Isaacson', 'Bigraphy', 'available'),
	(10023, 'I Am Malala', NULL, NULL, NULL, NULL, 'Malala Yusufzai', 'Biography', 'available'),
	(10024, 'The Story Of My Life', NULL, NULL, NULL, NULL, 'Helen Keller', 'Biography', 'available'),
	(10025, 'Nova', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10026, 'One Piece', NULL, NULL, NULL, NULL, 'Eiichiro Oda', 'Manga', 'available'),
	(10027, 'Naruto', NULL, NULL, NULL, NULL, 'Masashi Kishimoto', 'Manga', 'available'),
	(10028, 'Batman', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10029, 'Encyclopaedia', NULL, NULL, NULL, NULL, 'Arihant', 'Other', 'available'),
	(10030, 'Atlas', NULL, NULL, NULL, NULL, 'Arihant', 'Other', 'available'),
	(10031, 'Current Affairs', NULL, NULL, NULL, NULL, 'Success Publications', 'Other', 'available'),
	(10032, 'Old Newspapers', NULL, NULL, NULL, NULL, 'Times Of India', 'Other', 'available'),
	(10033, 'Witcher', NULL, NULL, NULL, NULL, 'Andej Sapkowski', 'Fantasy', 'available'),
	(10034, 'The Da Vinci Code', 'Vinay', 10, '2019-10-03', '2019-11-02', 'Dan Brown', 'Mystry', 'not available'),
	(10035, 'Avengers: Infinity War', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10036, 'Avengers: Endgame', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10037, 'English', NULL, NULL, NULL, NULL, 'Martin', 'Education', 'available'),
	(10038, 'Chemistry', 'Pratik', 12, '2019-10-03', '2019-10-16', 'Pradeep', 'Education', 'not available'),
	(10039, 'Physics', NULL, NULL, NULL, NULL, 'HC Verma', 'Education', 'available'),
	(10040, 'Chemistry', NULL, NULL, NULL, NULL, 'S Chand', 'Education', 'available'),
	(10041, 'Physics', NULL, NULL, NULL, NULL, 'Pradeep', 'Education', 'available'),
	(10042, 'English', NULL, NULL, NULL, NULL, 'Wren and Martin', 'Education', 'available'),
	(10043, 'Hindi', NULL, NULL, NULL, NULL, 'Arihant', 'Education', 'available'),
	(10044, 'Economics', NULL, NULL, NULL, NULL, 'S Chand', 'Education', 'available'),
	(10045, 'Social Science', NULL, NULL, NULL, NULL, 'S Chand', 'Education', 'available'),
	(10046, 'Chemistry', NULL, NULL, NULL, NULL, 'Arihant', 'Education', 'available'),
	(10047, 'Physics', NULL, NULL, NULL, NULL, 'Arihant', 'Education', 'available'),
	(10048, 'Maths', NULL, NULL, NULL, NULL, 'Arihant', 'Education', 'available'),
	(10049, 'English', NULL, NULL, NULL, NULL, 'Arihant', 'Education', 'available'),
	(10050, 'Dreams From My Father', NULL, NULL, NULL, NULL, 'Barack Obama', 'Biography', 'available'),
	(10051, 'Runs and Ruins', NULL, NULL, NULL, NULL, 'Sunil Gavaskar', 'Biography', 'available'),
	(10052, 'Economics', NULL, NULL, NULL, NULL, 'Amartya Sen', 'Education', 'available'),
	(10053, 'Civics', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10054, 'Economics', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10055, 'English', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10056, 'Social Science', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10057, 'Political Science', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10058, 'Maths', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10059, 'Geography', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10060, 'Science', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10061, 'Hindi', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10062, 'Biology', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10063, 'Chemistry', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10064, 'Physics', NULL, NULL, NULL, NULL, 'NCERT', 'Education', 'available'),
	(10065, 'Spiderman', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10066, 'Ironman', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10067, 'Black Widow', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10068, 'Captain America', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10069, 'Black Panther', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10070, 'Hawkeye', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10071, 'Doctor Strange', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10072, 'Antman', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10073, 'Vision', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10074, 'Hulk', NULL, NULL, NULL, NULL, 'Marvel Comics', 'Comic', 'available'),
	(10075, 'Superman', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10077, 'Aquaman', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10078, 'Wonder Woman', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10079, 'Watchman', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10080, 'Flash', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10081, 'Cyborg', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10082, 'Joker', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10083, 'Shazam', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10084, 'Green Lantern', NULL, NULL, NULL, NULL, 'DC Comics', 'Comic', 'available'),
	(10085, 'Death Note', NULL, NULL, NULL, NULL, 'Takeshi Obata', 'Manga', 'available'),
	(10086, 'Vampire Knight', NULL, NULL, NULL, NULL, 'Matsuri Hino', 'Manga', 'available'),
	(10087, 'Skip Beat', NULL, NULL, NULL, NULL, 'Tomo Kimura', 'Manga', 'available'),
	(10088, 'Case Closed', NULL, NULL, NULL, NULL, 'Gosho Aoyama', 'Manga', 'available'),
	(10089, 'Black Butler', NULL, NULL, NULL, NULL, 'Tite Kubo', 'Manga', 'available'),
	(10090, 'Beast Master', NULL, NULL, NULL, NULL, 'Kyousuke Motomi', 'Manga', 'available'),
	(10091, 'Dragon Ball', NULL, NULL, NULL, NULL, 'Akira Toriyama', 'Manga', 'available'),
	(10092, 'Attack On Titan', NULL, NULL, NULL, NULL, 'Sheldon Drzka', 'Manga', 'available'),
	(10093, 'Red River', NULL, NULL, NULL, NULL, 'Chie Sinohora', 'Manga', 'available'),
	(10094, 'From Far Away', NULL, NULL, NULL, NULL, 'Patrick Rothfuss', 'Fantasy', 'available'),
	(10095, 'The Name Of The Wind', NULL, NULL, NULL, NULL, 'Kyodo Hikawa', 'Fantasy', 'available'),
	(10096, 'The Way Of Kings', NULL, NULL, NULL, NULL, 'Brandon Sanderson', 'Fantasy', 'available'),
	(10097, 'A Wizard Of Earthsea', NULL, NULL, NULL, NULL, 'Ursula LeGuin', 'Fantasy', 'available'),
	(10098, 'Assassins Apprentice', NULL, NULL, NULL, NULL, 'Robin Hobb', 'Fantasy', 'available'),
	(10099, 'The Lies Of Locke Lamora', NULL, NULL, NULL, NULL, 'Scott Lynch', 'Fantasy', 'available'),
	(10100, 'Kushiels Dart', NULL, NULL, NULL, NULL, 'Jacqueline Carey', 'Fantasy', 'available'),
	(10101, 'American Gods', NULL, NULL, NULL, NULL, 'Neil Gaiman', 'Fantasy', 'available'),
	(10102, 'The Night Circus', NULL, NULL, NULL, NULL, 'Erin Morgenstern', 'Fantasy', 'available'),
	(10103, 'Moon Called', NULL, NULL, NULL, NULL, 'Patricia Briggs', 'Fantasy', 'available'),
	(10104, 'Pride and Prejudice', NULL, NULL, NULL, NULL, 'Jane Austen', 'Fiction', 'available'),
	(10105, 'Hamlet', NULL, NULL, NULL, NULL, 'William Shakespeare', 'Fiction', 'available'),
	(10106, 'The Laughing Monsters', NULL, NULL, NULL, NULL, 'Denis Johnson', 'Fiction', 'available'),
	(10107, 'Euphoria', NULL, NULL, NULL, NULL, 'Lily King', 'Fiction', 'available'),
	(10108, 'Station Eleven', NULL, NULL, NULL, NULL, 'Emily St John Mandel', 'Fiction', 'available'),
	(10109, 'Whiskey Tango Foxtrot', NULL, NULL, NULL, NULL, 'David Shafer', 'Fiction', 'available'),
	(10110, 'Wonderland', NULL, NULL, NULL, NULL, 'Stacey D Erasmo', 'Fiction', 'available'),
	(10111, 'Redeployment', NULL, NULL, NULL, NULL, 'Phil Klay', 'Fiction', 'available'),
	(10112, 'The Zone Of Interest', NULL, NULL, NULL, NULL, 'Martin Amis', 'Fiction', 'available'),
	(10113, 'The Bone Clocks', NULL, NULL, NULL, NULL, 'David Mitchell', 'Fiction', 'available'),
	(10114, 'Shoe Dog', NULL, NULL, NULL, NULL, 'Phil Knight', 'Biography', 'available'),
	(10115, 'The Everything Store', NULL, NULL, NULL, NULL, 'Brad Stone', 'Biography', 'available'),
	(10116, 'Sam Walton', NULL, NULL, NULL, NULL, 'John Huey', 'Biography', 'available'),
	(10117, 'Grinding It Out', NULL, NULL, NULL, NULL, 'Ray Kroc', 'Biography', 'available'),
	(10118, 'The Power Broker', NULL, NULL, NULL, NULL, 'Robert Caro', 'Biography', 'available'),
	(10119, 'Onward', NULL, NULL, NULL, NULL, 'Howard Schultz', 'Biography', 'available'),
	(10120, 'Frida', NULL, NULL, NULL, NULL, 'Hayden Herrera', 'Biography', 'available'),
	(10121, 'Alan Turning', NULL, NULL, NULL, NULL, 'Andrew Hodges', 'Biography', 'available'),
	(10122, 'Where Men Win Glory', NULL, NULL, NULL, NULL, 'Jon Krakauer', 'Biography', 'available'),
	(10123, 'Washington', 'Nishan', 11, '2019-10-03', '2019-10-23', 'Ron Chernow', 'Biography', 'not available'),
	(10124, 'The Woman In White', NULL, NULL, NULL, NULL, 'Wilkie Collins', 'Mystry', 'available'),
	(10125, 'The Name OF The Rose', NULL, NULL, NULL, NULL, 'Umberto Eco', 'Mystry', 'available'),
	(10126, 'The Girl On The Train', NULL, NULL, NULL, NULL, 'Paula Hawkins', 'Mystry', 'available'),
	(10127, 'Gone Girl', NULL, NULL, NULL, NULL, 'Gillian Flynn', 'Mystry', 'available'),
	(10128, 'The Alienist', NULL, NULL, NULL, NULL, 'Caleb Carr', 'Mystery', 'available'),
	(10129, 'Killing Floor', NULL, NULL, NULL, NULL, 'Lee Child', 'Mystery', 'available'),
	(10130, 'In The Woods', NULL, NULL, NULL, NULL, 'Tana French', 'Mystry', 'available'),
	(10131, 'Mystic River', NULL, NULL, NULL, NULL, 'Dennis Lehane', 'Mystry', 'available'),
	(10132, 'The Daughter Of Time', NULL, NULL, NULL, NULL, 'Josephine Tey', 'Mystry', 'available'),
	(10133, 'Sharp Objects', NULL, NULL, NULL, NULL, 'Gillian Flynn', 'Mystry', 'available'),
	(10134, 'Fifty Shades Of Grey', NULL, NULL, NULL, NULL, 'EL James', 'Romantic', 'available'),
	(10135, 'The Fault In Our Stars', NULL, NULL, NULL, NULL, 'John Green', 'Romantic', 'available'),
	(10136, 'Eleanor And Park', NULL, NULL, NULL, NULL, 'Rainbow Rowell', 'Romantic', 'available'),
	(10137, 'Bared To You', NULL, NULL, NULL, NULL, 'Sylvia Day', 'Romantic', 'available'),
	(10138, 'Outlander', NULL, NULL, NULL, NULL, 'Diana Gabaldon', 'Romantic', 'available'),
	(10139, 'Me Before You', NULL, NULL, NULL, NULL, 'Jojo Moyes', 'Romantic', 'available'),
	(10140, 'The Hating Game', NULL, NULL, NULL, NULL, 'Sally Thorne', 'Romantic', 'available'),
	(10141, 'Dark Lover', NULL, NULL, NULL, NULL, 'Jessica Bird', 'Romantic', 'available'),
	(10142, 'Love Story', NULL, NULL, NULL, NULL, 'Erich Segal', 'Romantic', 'available'),
	(10143, 'Naked In Death', 'Rohit', 11, '2019-10-03', '2019-10-22', 'Nora Roberts', 'Romantic', 'not available'),
	(10144, 'Beautiful Bastard', NULL, NULL, NULL, NULL, 'Christina Lauren', 'Romantic', 'available'),
	(10145, 'The Time Magazine', NULL, NULL, NULL, NULL, 'TIMES', 'Other', 'available'),
	(10146, 'Forbes Magazines', NULL, NULL, NULL, NULL, 'Forbes', 'Other', 'available'),
	(10147, 'Hindi Sahitya', NULL, NULL, NULL, NULL, 'Gita Publications', 'Other', 'available'),
	(10148, 'Champak', NULL, NULL, NULL, NULL, 'Childhood Publications', 'Other', 'available'),
	(10149, 'India Today', NULL, NULL, NULL, NULL, 'Living Media Publications', 'Other', 'available'),
	(10150, 'The Week Magazine', NULL, NULL, NULL, NULL, 'Dennis Publications', 'Other', 'available'),
	(10151, 'Vogue', NULL, NULL, NULL, NULL, 'Conde Nast', 'Other', 'available'),
	(10152, 'Sportstar', NULL, NULL, NULL, NULL, 'The Hindu', 'Other', 'available'),
	(10153, 'Outlook', NULL, NULL, NULL, NULL, 'Jaico Publications', 'Other', 'available'),
	(10154, 'Rock Street Journal', NULL, NULL, NULL, NULL, 'Amit Saigal', 'Other', 'available'),
	(10155, 'Pratiyogita Darpan', NULL, NULL, NULL, NULL, 'Success Publications', 'Other', 'available')
""")
mycon.commit()
